# Generated by Django 4.2.7 on 2023-11-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.CharField(max_length=3)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='api.section')),
                ('sideLeft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideLeft', to='api.section')),
                ('sideRight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideRight', to='api.section')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('earnings', models.FloatField()),
                ('active', models.BooleanField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.block')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('row', models.CharField(max_length=3)),
                ('column', models.IntegerField()),
                ('available', models.BooleanField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seat'),
        ),
        migrations.AddField(
            model_name='block',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
    ]
