# Generated by Django 4.2.7 on 2023-11-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_block_venue_show_seat_block_seats_block_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='api.section'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sideLeft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sideLeft', to='api.section'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sideRight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sideRight', to='api.section'),
        ),
    ]
